export const DEFAULT_FILLERS: readonly string[] = [
  // Hesitation sounds — Chrome often drops these but sometimes transcribes variants
  "um",
  "umm",
  "uh",
  "uhh",
  "uhm",
  "hmm",
  "hm",
  "mmm",
  "mhm",
  "huh",
  "er",
  "err",
  "eh",
  "ah",
  "ahh",
  "ahem",
  // Discourse markers & hedges Chrome reliably transcribes
  "like",
  "you know",
  "you know what i mean",
  "i mean",
  "i guess",
  "i think",
  "i suppose",
  "i would say",
  "sort of",
  "sorta",
  "kind of",
  "kinda",
  "pretty much",
  "basically",
  "literally",
  "actually",
  "seriously",
  "honestly",
  "obviously",
  "clearly",
  "essentially",
  "definitely",
  "totally",
  "really",
  "just",
  // Openers, closers & connective crutches
  "so",
  "well",
  "right",
  "okay",
  "anyway",
  "anyways",
  "now",
  "look",
  "listen",
  "regardless",
  "to be honest",
  "to be fair",
  "you see",
  // Trailing / vague-ending fillers
  "or something",
  "or whatever",
  "and stuff",
  "at the end of the day",
  "like i said",
];
